# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stairdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stair',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
