# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stairdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stair',
            name='coords',
        ),
        migrations.AddField(
            model_name='stair',
            name='coords_x',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='stair',
            name='coords_y',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
