# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stairdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='stairid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='stairdb.Stair'),
        ),
    ]
