# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-09 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stairdb', '0002_auto_20170512_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='stair',
            name='handrail',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='stair',
            name='stair_ct',
            field=models.IntegerField(null=True),
        ),
    ]
