# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stairdb', '0003_auto_20170216_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stair',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
