# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stairdb', '0004_auto_20171109_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stair',
            name='name',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stair',
            name='stair_ct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stair',
            name='handrail',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='stair',
            name='location',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stair',
            name='type',
            field=models.CharField(blank=True, choices=[('Alley Stairs', 'Alley Stairs'), ('Building Access', 'Building Access'), ('Country Park Stairs', 'Country Park Stairs'), ('Curb Stairs', 'Curb Stairs'), ('Elevated Walkway', 'Elevated Walkway'), ('Escalator', 'Escalator'), ('Footpath', 'Footpath'), ('Maintenance Stairs', 'Maintenance Stairs'), ('Pier Stairs', 'Pier Stairs'), ('Park Stairs', 'Park Stairs'), ('Plaza Stairs', 'Plaza Stairs'), ('Street Stairs', 'Street Stairs'), ('Subway', 'Subway')], max_length=25, null=True),
        ),
    ]
