# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-03 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stairdb', '0005_auto_20171213_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='md5sum',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='stair',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stair',
            name='materials',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('stone', 'Stone'), ('pre-cast', 'Pre-cast concrete'), ('cast-in-place', 'Cast in place concrete (CIP)'), ('tile', 'Tile'), ('brick', 'Brick'), ('wood', 'Wood'), ('metal', 'Metal'), ('plastic', 'Plastic/composite'), ('other', 'Other')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='stair',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
