# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-07 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import stairdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('stairdb', '0006_auto_20190503_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(storage=stairdb.models.PrepareStorage(), upload_to='photos/'),
        ),
    ]
