# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stairdb', '0006_stair_centroid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stair',
            name='centroid',
        ),
    ]
